### ISSUE TITLE
What do I need to get started?

### ISSUE THREAD

**Issue by MrYossu** [qingpeng9802/vscode-common-lisp#1]
Suppose I have a clean install of Windows 10, and I install VS Code. What else do I need to develop Lisp with your extension?

What I mean is, does this extension include Lisp itself, or does it assume I already have Lisp (and maybe other requirements) installed? If so, what else do I need?

Thanks

**Comment by qingpeng9802** [comment]
No, this extension doesn't include Lisp and will not install Lisp. This extension will only influence the language features in VS Code.

If you don't need a package manager now, just installing Lisp is enough to start. 
https://lispcookbook.github.io/cl-cookbook/getting-started.html is a good start.
