### ISSUE TITLE
Some code directly after a comma cannot be recognized and colored.

### ISSUE THREAD

**Issue by skr2005** [qingpeng9802/vscode-common-lisp#12]
> Please help confirm if it is a purely Textmate grammar issue:
> 1. set `"commonLisp.StaticAnalysis.enabled": false` in this extension's built-in settings (under `Common Lisp` tab) or set `"editor.semanticHighlighting.enabled": false` in VS Code's settings.
> 2. reload VS Code.
> 3. check if you still see the bug and describe your findings.

**I have restarted VSCode with `"commonLisp.StaticAnalysis.enabled"` disabled, and the imperfection still exists.**

-   VS Code Version: 1.89.1 (user setup)
-   Desktop Electron Version or Browser version: 28.2.8
-   OS Version: Win11 23H2

**Describe the bug**
**Special variables, constants, numbers, and `nil` have no color in backquote list after a comma. However, they can still be recognized when put in an additional list.**

**Code**
```lsp
;; Please include a code snippet that demonstrates the issue
(defparameter *test* 4)
(defconstant +test+ 6)

(print `(a b c ,(1- *test*) ,*test* ,(1- +test+) ,+test+ ,7 7 ,'(nil) ,nil))
```

**Current Behavior Screenshot**
![220424](https://github.com/qingpeng9802/vscode-common-lisp/assets/62237294/8d9da732-cd37-40e5-a7c6-1da523f25332)

**Comment by qingpeng9802** [comment]
Thank you for your report. This issue should be resolved by [79d04dc](https://github.com/qingpeng9802/vscode-common-lisp/commit/79d04dc9ca80d98e65c4f28b3d67a24a7829b18f), and the solution has been released in v1.2.11.
