### ISSUE TITLE
是否可以帮助制作方言Lisp的插件

### ISSUE THREAD

**Issue by renchaoroy** [qingpeng9802/vscode-common-lisp#4]
Li ,你好，感觉上你是中国人，所以直接用中文冒昧跟你联系。
我在工作中是使用Creo Elements Direct Modeling软件做机械设计，我在尝试开发一些在Creo Elements Direct Modeling中使用的增强效率的小插件，Creo Elements Direct Modeling 使用的开发语言是CL，我看到你开发的在VS Code中使用的CL智能提示插件，非常惊叹。所以想请你看看没有可能把Creo Elements Direct Modeling的指令和函数也整合进去，形成一个定制版的插件。希望要的效果就跟你现在的插件效果一样，有颜色的识别，有悬停提示，有智能补全，还有网页链接。

Creo Elements Direct Modeling命令和函数URL:
https://support.ptc.com/help/creo_elements_direct/r20.5.0.0/advanced_documentation/integration_kit/comref/comref_idx.html

https://support.ptc.com/help/creo_elements_direct/r20.5.0.0/advanced_documentation/integration_kit/reference/function_index.html

我的联系方式是renchao_roy@hotmail.com
谢谢！

**Comment by qingpeng9802** [comment]
邮件回复
