### ISSUE TITLE
Use in Linguist?

### ISSUE THREAD

**Issue by TheWitheredStriker** [qingpeng9802/vscode-common-lisp#7]
**Is your feature request related to a problem? Please describe.**
Common Lisp's syntax highlighting on GitHub is currently provided by [lisp.tmbundle](https://github.com/textmate/lisp.tmbundle), but this grammar is outdated and abandoned. For example, it does not highlight block comments or keyword symbols, and other things are only partially highlighted.

**Describe the solution you'd like**
I wanted to ask if you could consider submitting your VS Code extension's grammar (the tmLanguage file) to [Linguist](https://github.com/github-linguist/linguist), using [this method](https://github.com/github-linguist/linguist/blob/master/CONTRIBUTING.md#changing-the-source-of-a-syntax-highlighting-grammar).

**Describe alternatives you've considered**
Writing my own grammar. This seems like redundant work though, you have a much better one already.

**Additional context**
Compare:

![image](https://github.com/qingpeng9802/vscode-common-lisp/assets/38614982/d1bfe4e2-9fec-4b46-8071-e58af16aaf16)
![image](https://github.com/qingpeng9802/vscode-common-lisp/assets/38614982/d00754d5-806f-491a-98c0-555bcfeb4690)

![image](https://github.com/qingpeng9802/vscode-common-lisp/assets/38614982/37b72791-d04f-4901-8531-8500ed973f22)
![image](https://github.com/qingpeng9802/vscode-common-lisp/assets/38614982/4c978ac6-ac5d-471b-86d6-fbe90019e60e)

![image](https://github.com/qingpeng9802/vscode-common-lisp/assets/38614982/c4df87f7-0b24-45ff-9552-23177913d397)
![image](https://github.com/qingpeng9802/vscode-common-lisp/assets/38614982/5c87c36a-c625-4efd-8615-b1febd0b07d3)

**Comment by qingpeng9802** [comment]
I investigated the use of [lisp.tmbundle](https://github.com/textmate/lisp.tmbundle) by GitHub a long time ago, but I did not dig into [Linguist](https://github.com/github-linguist/linguist). If this grammar is provided as GitHub syntax, it will involve some supply chain issues (like differences in grammar colors and users demands). I may prefer to open a new pure textmate grammar repo to deal with the issue. Let me hold this and think for a while.

**Comment by qingpeng9802** [comment]
The syntax highlighting has been deployed to GitHub by Linguist. The repo for GitHub highlighting is at [common-lisp-tmlanguage](https://github.com/qingpeng9802/common-lisp-tmlanguage).

By the way, you may already know, you can press `.` on the keyboard to be redirected to github.dev to get the same extension experience as in vscode. See [the-githubdev-web-based-editor](https://docs.github.com/en/codespaces/the-githubdev-web-based-editor) 😀

**Comment by TheWitheredStriker** [comment]
Awesome! Thank you!
